name: build-deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Jar File
      run: ./gradlew clean build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qna-backend:$(date +%s)
